#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
	#
	# ${EWW} --config "$CFG" close \
	# 				background profile system clock uptime music github \
	# 				reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	# rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--tg" ]]; then
	close_dash && telegram-desktop &

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && thunar ~ &

elif [[ "$1" == "--ge" ]]; then
	close_dash && geany &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--gp" ]]; then
	close_dash && gimp &

elif [[ "$1" == "--vb" ]]; then
	close_dash && virtualbox &

elif [[ "$1" == "--browser" ]]; then
	close_dash && brave &

elif [[ "$1" == "--warp" ]]; then
	close_dash && warp-terminal &

elif [[ "$1" == "--postman" ]]; then
close_dash && postman &

elif [[ "$1" == "--spotify" ]]; then
close_dash && spotify &

elif [[ "$1" == "--simplenote" ]]; then
close_dash && simplenote -no-sandbox &

elif [[ "$1" == "--torrent" ]]; then
close_dash && qbittorrent &

elif [[ "$1" == "--obsidian" ]]; then
  close_dash && obsidian &
fi
