require "settings"
require "plugins"
require "mappings"
--> Theme
require "colorschemes-config"
require "lualine-config"
--> NerdTree
require "nvim-tree-config"
--> FZF
require "telescope-config"
--> Git
require "gitsigns-config"
--> Indenline
require "indentline-config"
--> CMP
require "cmp-config"
--> LSP
require "lsp-config"
--> HOP
require "hop-config"
--> Treesitter
require "treesitter-config"
--> Autopairs
require "autopairs-config"
