#!/usr/bin/env zsh

FIRST_CHARACTER_OK=""
FIRST_CHARACTER_KO=""
DIRTY="✘ "
NONE="✔ "

prompt_arch_pwd() {
  prompt_short_dir=$("$DOTLY_PATH/bin/dot" core short_pwd)
  print -n "%F{yellow}${prompt_short_dir}"
}

prompt_arch_git() {
  [[ -n ${git_info} ]] && print -n "%F{white} on${(e)git_info[prompt]}"
}

prompt_arch_precmd() {
  (( ${+functions[git-info]} )) && git-info
}

prompt_arch_setup() {
  local prompt_arch_status='%(?:%F{blue}:%F{red})'

  autoload -Uz add-zsh-hook && add-zsh-hook precmd prompt_arch_precmd

  prompt_opts=(cr percent sp subst)

  zstyle ':zim:git-info:branch' format '%F{green}%b'
  zstyle ':zim:git-info:commit' format '%c'
  zstyle ':zim:git-info:clean' format '%F{green}$NONE'
  zstyle ':zim:git-info:dirty' format '%F{red}$DIRTY'
  zstyle ':zim:git-info:keys' format 'prompt' ' %F{cyan}%b%c %C%D'

  PS1="${prompt_arch_status} \$(prompt_arch_pwd)\$(prompt_arch_git)%f "
  RPS1=''
}

prompt_arch_setup "${@}"
