#!/bin/bash

icon_path="$HOME/.config/mako/icons/changevolume.svg"
function send_notification() {
	volume=$(pamixer --get-volume)
	notify-send -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "$icon_path" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	current_volume=$(pamixer --get-volume)
	if [ "$current_volume" -lt 100 ]; then
		pamixer -i 5 --allow-boost
	fi
	send_notification $1
	;;
down)
	pamixer -u
	pamixer -d 5 --allow-boost
	send_notification $1
	;;
mute)
	pamixer -t
	if $(pamixer --get-mute); then
		notify-send -i volume-mute -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
