# STARSHIP
# Spaceship prompt configuration
# Just comment a section if you want to disable it
SPACESHIP_PROMPT_ORDER=(
  #time           # Time stamps section
  user           # Username section
  dir            # Current directory section
  host           # Hostname section
  git            # Git section (git_branch + git_status)
  #hg             # Mercurial section (hg_branch  + hg_status)
  package        # Package version
  node           # Node.js section
  #bun            # Bun section
  #deno           # Deno section
  ruby           # Ruby section
  python         # Python section
  #elm            # Elm section
  #elixir         # Elixir section
  #xcode          # Xcode section
  #swift          # Swift section
  golang         # Go section
  #perl           # Perl section
  php            # PHP section
  rust           # Rust section
  #haskell        # Haskell Stack section
  #scala          # Scala section
  #kotlin         # Kotlin section
  java           # Java section
  lua            # Lua section
  dart           # Dart section
  #julia          # Julia section
  #crystal        # Crystal section
  docker         # Docker section
  docker_compose # Docker section
  aws            # Amazon Web Services section
  gcloud         # Google Cloud Platform section
  azure          # Azure section
  venv           # virtualenv section
  conda          # conda virtualenv section
  dotnet         # .NET section
  #ocaml          # OCaml section
  #vlang          # V section
  #zig            # Zig section
  purescript     # PureScript section
  erlang         # Erlang section
  kubectl        # Kubectl context section
  #ansible        # Ansible section
  #terraform      # Terraform workspace section
  #pulumi         # Pulumi stack section
  #ibmcloud       # IBM Cloud section
  #nix_shell      # Nix shell
  #gnu_screen     # GNU Screen section
  exec_time      # Execution time
  async          # Async jobs indicator
  line_sep       # Line break
  #battery        # Battery level and status
  jobs           # Background jobs indicator
  exit_code      # Exit code section
  sudo           # Sudo indicator
  char           # Prompt character
)

# Ansible
#SPACESHIP_ANSIBLE_SHOW=true
SPACESHIP_ANSIBLE_SHOW=false
SPACESHIP_ANSIBLE_ASYNC=true
SPACESHIP_ANSIBLE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_ANSIBLE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_ANSIBLE_SYMBOL="🅐"
SPACESHIP_ANSIBLE_COLOR="white"

# Async
SPACESHIP_ASYNC_SHOW=true
SPACESHIP_ASYNC_SHOW_COUNT=false
SPACESHIP_ASYNC_PREFIX=""
SPACESHIP_ASYNC_SUFFIX=""
SPACESHIP_ASYNC_SYMBOL=""
SPACESHIP_ASYNC_COLOR="gray"

# AWS
SPACESHIP_AWS_SHOW=true
SPACESHIP_AWS_PREFIX="using·"
SPACESHIP_AWS_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_AWS_SYMBOL="☁️·"
SPACESHIP_AWS_COLOR=208

# Azure
SPACESHIP_AZURE_SHOW=true
SPACESHIP_AZURE_PREFIX="using"
SPACESHIP_AZURE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_AZURE_SYMBOL="☁️"
SPACESHIP_AZURE_COLOR=039

# Battery
#SPACESHIP_BATTERY_SHOW=true
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_BATTERY_ASYNC=true
SPACESHIP_BATTERY_PREFIX=""
SPACESHIP_BATTERY_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_BATTERY_SYMBOL_CHARGING="⇡"
SPACESHIP_BATTERY_SYMBOL_DISCHARGING="⇣"
SPACESHIP_BATTERY_SYMBOL_FULL="•"
SPACESHIP_BATTERY_THRESHOLD=10

# Bun
#SPACESHIP_BUN_SHOW=true
SPACESHIP_BUN_SHOW=false
SPACESHIP_BUN_ASYNC=true
SPACESHIP_BUN_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_BUN_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_BUN_SYMBOL="🍞"
SPACESHIP_BUN_COLOR="#fbf0df"

# Conda
SPACESHIP_CONDA_SHOW=true
SPACESHIP_CONDA_ASYNC=false
SPACESHIP_CONDA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_CONDA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_CONDA_SYMBOL="🅒·"
SPACESHIP_CONDA_COLOR="blue"
SPACESHIP_CONDA_VERBOSE=true

# Crystal
#SPACESHIP_CRYSTAL_SHOW=true
SPACESHIP_CRYSTAL_SHOW=false
SPACESHIP_CRYSTAL_ASYNC=true
SPACESHIP_CRYSTAL_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_CRYSTAL_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_CRYSTAL_SYMBOL="🔮"
SPACESHIP_CRYSTAL_SYMBOL=""
SPACESHIP_CRYSTAL_COLOR="069"

# Dart
SPACESHIP_DART_SHOW=true
SPACESHIP_DART_ASYNC=true
SPACESHIP_DART_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_DART_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DART_SYMBOL="🎯·"
SPACESHIP_DART_COLOR="blue"

# Deno
#SPACESHIP_DENO_SHOW=true
SPACESHIP_DENO_SHOW=false
SPACESHIP_DENO_ASYNC=true
SPACESHIP_DENO_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_DENO_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DENO_SYMBOL="🦕·"
SPACESHIP_DENO_DEFAULT_VERSION=""
SPACESHIP_DENO_COLOR="cyan"

# DIR
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_PREFIX="in·"
SPACESHIP_DIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DIR_TRUNC=2
SPACESHIP_DIR_TRUNC_PREFIX="/"
SPACESHIP_DIR_COLOR="#98971A"
SPACESHIP_DIR_LOCK_SYMBOL=" "
SPACESHIP_DIR_LOCK_COLOR="#FB4934"

# Docker
SPACESHIP_DOCKER_SHOW=true
SPACESHIP_DOCKER_ASYNC=true
SPACESHIP_DOCKER_PREFIX=on
SPACESHIP_DOCKER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_DOCKER_SYMBOL="🐳·"
SPACESHIP_DOCKER_SYMBOL=" "
SPACESHIP_DOCKER_COLOR="#3291E5"
SPACESHIP_DOCKER_VERBOSE=false
SPACESHIP_DOCKER_CONTEXT_PREFIX="·("
SPACESHIP_DOCKER_CONTEXT_SUFFIX=")"

# Docker Compose
SPACESHIP_DOCKER_COMPOSE_SHOW=true
SPACESHIP_DOCKER_COMPOSE_ASYNC=true
SPACESHIP_DOCKER_COMPOSE_PREFIX=runs
SPACESHIP_DOCKER_COMPOSE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DOCKER_COMPOSE_SYMBOL="🐙"
SPACESHIP_DOCKER_COMPOSE_COLOR="cyan"
SPACESHIP_DOCKER_COMPOSE_COLOR_UP="green"
SPACESHIP_DOCKER_COMPOSE_COLOR_DOWN="red"
SPACESHIP_DOCKER_COMPOSE_COLOR_PAUSED="yellow"

# Dotnet
SPACESHIP_DOTNET_SHOW=true
SPACESHIP_DOTNET_ASYNC=true
SPACESHIP_DOTNET_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_DOTNET_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DOTNET_SYMBOL=".NET·"
SPACESHIP_DOTNET_COLOR="#6A4097"

# Elixir
#SPACESHIP_ELIXIR_SHOW=true
SPACESHIP_ELIXIR_SHOW=false
SPACESHIP_ELIXIR_ASYNC=true
SPACESHIP_ELIXIR_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_ELIXIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_ELIXIR_DEFAULT_VERSION=""
SPACESHIP_ELIXIR_SYMBOL="💧·"
SPACESHIP_ELIXIR_COLOR="magenta"

# Elm
#SPACESHIP_ELM_SHOW=true
SPACESHIP_ELM_SHOW=false
SPACESHIP_ELM_ASYNC=true
SPACESHIP_ELM_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_ELM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_ELM_SYMBOL="🌳·"
SPACESHIP_ELM_COLOR="cyan"

# Erlang
#SPACESHIP_ERLANG_SHOW=true
SPACESHIP_ERLANG_SHOW=false
SPACESHIP_ERLANG_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_ERLANG_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_ERLANG_SYMBOL="𝐞"
SPACESHIP_ERLANG_COLOR="red"

# Execution Time
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_PREFIX="took "
SPACESHIP_EXEC_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_EXEC_TIME_COLOR="#FABD2F"
SPACESHIP_EXEC_TIME_ELAPSED=2
SPACESHIP_EXEC_TIME_PRECISION=1

# Exit Code
SPACESHIP_EXIT_CODE_SHOW=false
SPACESHIP_EXIT_CODE_PREFIX=""
SPACESHIP_EXIT_CODE_SUFFIX=""
SPACESHIP_EXIT_CODE_SYMBOL="✘"
SPACESHIP_EXIT_CODE_COLOR="#FB4934"

# GIT
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_PREFIX="on "
SPACESHIP_GIT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GIT_SYMBOL=" "
SPACESHIP_GIT_ORDER=(git_branch git_status)

# GIT BRANCH
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_BRANCH_ASYNC=false
SPACESHIP_GIT_BRANCH_PREFIX="$SPACESHIP_GIT_SYMBOL"
SPACESHIP_GIT_BRANCH_SUFFIX=""
SPACESHIP_GIT_BRANCH_COLOR="#B16286"

# GIT STATUS
SPACESHIP_GIT_STATUS_SHOW=true
SPACESHIP_GIT_STATUS_ASYNC=true
SPACESHIP_GIT_STATUS_PREFIX=" ["
SPACESHIP_GIT_STATUS_SUFFIX="]"
SPACESHIP_GIT_STATUS_COLOR="#FB4934"
SPACESHIP_GIT_STATUS_UNTRACKED="?"
SPACESHIP_GIT_STATUS_ADDED="+"
SPACESHIP_GIT_STATUS_MODIFIED="!"
SPACESHIP_GIT_STATUS_RENAMED="»"
SPACESHIP_GIT_STATUS_DELETED="✘"
SPACESHIP_GIT_STATUS_STASHED="S"
SPACESHIP_GIT_STATUS_UNMERGED=""
SPACESHIP_GIT_STATUS_AHEAD="⇡"
SPACESHIP_GIT_STATUS_BEHIND="⇣"
SPACESHIP_GIT_STATUS_DIVERGED="⇕"

# GNU Screen
#SPACESHIP_GNU_SCREEN_SHOW=true
SPACESHIP_GNU_SCREEN_SHOW=false
SPACESHIP_GNU_SCREEN_ASYNC=false
SPACESHIP_GNU_SCREEN_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_GNU_SCREEN_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GNU_SCREEN_SYMBOL="💻"
SPACESHIP_GNU_SCREEN_COLOR="#FABD2F"

# Go
SPACESHIP_GOLANG_SHOW=true
SPACESHIP_GOLANG_ASYNC=true
SPACESHIP_GOLANG_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_GOLANG_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_GOLANG_SYMBOL="🐹·"
SPACESHIP_GOLANG_SYMBOL="·"
SPACESHIP_GOLANG_COLOR="#6EC1D0"

# Google Cloud
#SPACESHIP_GCLOUD_SHOW=true
SPACESHIP_GCLOUD_SHOW=false
SPACESHIP_GCLOUD_ASYNC=true
SPACESHIP_GCLOUD_PREFIX="using·"
SPACESHIP_GCLOUD_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GCLOUD_SYMBOL="☁️·"
SPACESHIP_GCLOUD_COLOR=26

# Haskell
#SPACESHIP_HASKELL_SHOW=true
SPACESHIP_HASKELL_SHOW=false
SPACESHIP_HASKELL_ASYNC=true
SPACESHIP_HASKELL_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_HASKELL_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_HASKELL_SYMBOL="λ·"
SPACESHIP_HASKELL_SYMBOL="·"
SPACESHIP_HASKELL_COLOR="#FB4934"

# Hostname HOST
SPACESHIP_HOST_SHOW=true
SPACESHIP_HOST_SHOW_FULL=false
SPACESHIP_HOST_PREFIX="at·"
SPACESHIP_HOST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_HOST_COLOR="#458588"
SPACESHIP_HOST_COLOR_SSH="#B8BB26"

# IMB Cloud
#SPACESHIP_IBMCLOUD_SHOW=true
SPACESHIP_IBMCLOUD_SHOW=false
SPACESHIP_IBMCLOUD_ASYNC=true
SPACESHIP_IBMCLOUD_PREFIX="using·"
SPACESHIP_IBMCLOUD_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_IBMCLOUD_SYMBOL="·"
SPACESHIP_IBMCLOUD_COLOR=39

# Java
SPACESHIP_JAVA_SHOW=true
SPACESHIP_JAVA_ASYNC=true
SPACESHIP_JAVA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_JAVA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_JAVA_SYMBOL="☕·"
SPACESHIP_JAVA_SYMBOL="·"
SPACESHIP_JAVA_COLOR="#D3869B"

# Jobs
#SPACESHIP_JOBS_SHOW=true
SPACESHIP_JOBS_SHOW=false
SPACESHIP_JOBS_PREFIX=""
SPACESHIP_JOBS_SUFFIX="·"
SPACESHIP_JOBS_SYMBOL="✦"
SPACESHIP_JOBS_COLOR="#458588"
SPACESHIP_JOBS_AMOUNT_PREFIX=""
SPACESHIP_JOBS_AMOUNT_SUFFIX=""
SPACESHIP_JOBS_AMOUNT_THRESHOLD=1

# Julia
#SPACESHIP_JULIA_SHOW=true
SPACESHIP_JULIA_SHOW=false
SPACESHIP_JULIA_ASYNC=true
SPACESHIP_JULIA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_JULIA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_JULIA_SYMBOL="ஃ·"
SPACESHIP_JULIA_COLOR="#B8BB26"

# Kotlin
#SPACESHIP_KOTLIN_SHOW=true
SPACESHIP_KOTLIN_SHOW=false
SPACESHIP_KOTLIN_ASYNC=true
SPACESHIP_KOTLIN_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_KOTLIN_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_KOTLIN_SYMBOL="🅺"
SPACESHIP_KOTLIN_SYMBOL=""
SPACESHIP_KOTLIN_COLOR="#D3869B"

# Kubernetes
SPACESHIP_KUBECTL_SHOW=true
SPACESHIP_KUBECTL_ASYNC=true
SPACESHIP_KUBECTL_PREFIX="at·"
SPACESHIP_KUBECTL_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECTL_COLOR="white"
SPACESHIP_KUBECTL_SYMBOL="☸️·"
# Kubernetes version
SPACESHIP_KUBECTL_VERSION_SHOW=true
SPACESHIP_KUBECTL_VERSION_ASYNC=true
SPACESHIP_KUBECTL_VERSION_PREFIX=""
SPACESHIP_KUBECTL_VERSION_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECTL_VERSION_COLOR="#83A598"
# Kubernetes context
SPACESHIP_KUBECTL_CONTEXT_SHOW=true
SPACESHIP_KUBECTL_CONTEXT_PREFIX="at·"
SPACESHIP_KUBECTL_CONTEXT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECTL_CONTEXT_COLOR="#83A598"
SPACESHIP_KUBECTL_CONTEXT_SHOW_NAMESPACE=true
SPACESHIP_KUBECTL_CONTEXT_COLOR_GROUPS=""

# Line separator
SPACESHIP_PROMPT_SEPARATE_LINE=true

# Lua
SPACESHIP_LUA_SHOW=true
SPACESHIP_LUA_ASYNC=true
SPACESHIP_LUA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_LUA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_LUA_SYMBOL="🌙"
SPACESHIP_LUA_SYMBOL=""
SPACESHIP_LUA_COLOR="#00007D"

# Mercurial
#SPACESHIP_HG_SHOW=true
SPACESHIP_HG_SHOW=false
SPACESHIP_HG_ASYNC=true
SPACESHIP_HG_PREFIX="on·"
SPACESHIP_HG_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_HG_SYMBOL="☿·"
SPACESHIP_HG_ORDER=(hg_branch hg_status)
# Mercurial branch
#SPACESHIP_HG_BRANCH_SHOW=true
SPACESHIP_HG_BRANCH_SHOW=false
SPACESHIP_HG_BRANCH_ASYNC=true
SPACESHIP_HG_BRANCH_PREFIX="$SPACESHIP_HG_SYMBOL"
SPACESHIP_HG_BRANCH_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_HG_BRANCH_COLOR="#D3869B"
# Mercurial status
#SPACESHIP_HG_STATUS_SHOW=true
SPACESHIP_HG_STATUS_SHOW=false
SPACESHIP_HG_STATUS_ASYNC=true
SPACESHIP_HG_STATUS_PREFIX="["
SPACESHIP_HG_STATUS_SUFFIX="]"
SPACESHIP_HG_STATUS_COLOR="#FB4934"
SPACESHIP_HG_STATUS_UNTRACKED="?"
SPACESHIP_HG_STATUS_ADDED="+"
SPACESHIP_HG_STATUS_MODIFIED="!"
SPACESHIP_HG_STATUS_DELETED="✘"

# Nix shell
#SPACESHIP_NIX_SHELL_SHOW=true
SPACESHIP_NIX_SHELL_SHOW=false
SPACESHIP_NIX_SHELL_ASYNC=false
SPACESHIP_NIX_SHELL_PREFI="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_NIX_SHELL_SUFFI="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_NIX_SHELL_SYMBO="❄"
SPACESHIP_NIX_SHELL_COLOR="#FABD2F"

# Node
SPACESHIP_NODE_SHOW=true
SPACESHIP_NODE_ASYNC=true
SPACESHIP_NODE_PREFI="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_NODE_SUFFI="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_NODE_SYMBO="⬢·"
SPACESHIP_NODE_COLOR=green
SPACESHIP_NODE_DEFAULT_VERSION=""

# OCaml (deno)
#SPACESHIP_OCAML_SHOW=true
SPACESHIP_OCAML_SHOW=false
SPACESHIP_OCAML_ASYNC=true
SPACESHIP_OCAML_PREFI="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_OCAML_SUFFI="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_OCAML_SYMBO="🐫"
SPACESHIP_OCAML_COLOR="#FABD2F"

# Package
SPACESHIP_PACKAGE_SHOW=true
SPACESHIP_PACKAGE_ASYNC=true
SPACESHIP_PACKAGE_SHOW_PRIVATE=false
SPACESHIP_PACKAGE_PREFIX="is·"
SPACESHIP_PACKAGE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_PACKAGE_SYMBOL="📦·"
SPACESHIP_PACKAGE_COLOR="#FB4934"

# Perl
#SPACESHIP_PERL_SHOW=true
SPACESHIP_PERL_SHOW=false
SPACESHIP_PERL_ASYNC=true
SPACESHIP_PERL_PREFI="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PERL_SUFFI="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_PERL_SYMBO="🐪·"
SPACESHIP_PERL_COLOR="#458588"

# PHP
SPACESHIP_PHP_SHOW=true
SPACESHIP_PHP_ASYNC=true
SPACESHIP_PHP_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PHP_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_PHP_SYMBOL="🐘·"
SPACESHIP_PHP_SYMBOL=" "
SPACESHIP_PHP_COLOR="#777BB3"

# Prompt character (char)
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_PREFIX=" "
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SYMBOL_SUCCESS="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_SYMBOL_FAILURE="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_SYMBOL_ROOT="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_SYMBOL_SECONDARY="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_COLOR_SUCCESS="#1793D1"
SPACESHIP_CHAR_COLOR_FAILURE="#FB4934"
SPACESHIP_CHAR_COLOR_SECONDARY="#FABD2F"
SPACESHIP_PROMPT_ADD_NEWLINE=false

#SPACESHIP_PROMPT_SEPARATE_LINE=true
#SPACESHIP_PROMPT_PREFIXES_SHOW=true
#SPACESHIP_PROMPT_SUFFIXES_SHOW=true
#SPACESHIP_PROMPT_DEFAULT_PREFIX="via "
#SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "

# Pulumi
#SPACESHIP_PULUMI_SHOW=true
SPACESHIP_PULUMI_SHOW=false
SPACESHIP_PULUMI_ASYNC=true
SPACESHIP_PULUMI_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PULUMI_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_PULUMI_SYMBOL=""
SPACESHIP_PULUMI_COLOR=133

# PureScript
#SPACESHIP_PURESCRIPT_SHOW=true
SPACESHIP_PURESCRIPT_SHOW=false
SPACESHIP_PURESCRIPT_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PURESCRIPT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_PURESCRIPT_SYMBOL="⇔"
SPACESHIP_PURESCRIPT_COLOR="#EBDBB2"

# Python
SPACESHIP_PYTHON_SHOW=true
SPACESHIP_PYTHON_ASYNC=true
SPACESHIP_PYTHON_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PYTHON_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_PYTHON_SYMBOL="🐍·"
SPACESHIP_PYTHON_SYMBOL="·"
SPACESHIP_PYTHON_COLOR="#3570A0"

# Ruby
SPACESHIP_RUBY_SHOW=true
SPACESHIP_RUBY_ASYNC=true
SPACESHIP_RUBY_PREFI="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_RUBY_SUFFI="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_RUBY_SYMBO="💎·"
SPACESHIP_RUBY_SYMBOL="·"
SPACESHIP_RUBY_COLOR="#D30001"

# Rust
SPACESHIP_RUST_SHOW=true
SPACESHIP_RUST_ASYNC=true
SPACESHIP_RUST_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_RUST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_RUST_SYMBOL="🦀·"
SPACESHIP_RUST_SYMBOL="·"
SPACESHIP_RUST_COLOR="#EB4601"
SPACESHIP_RUST_VERBOSE_VERSION=false

# Scala
#SPACESHIP_SCALA_SHOW=true
SPACESHIP_SCALA_SHOW=false
SPACESHIP_SCALA_ASYNC=true
SPACESHIP_SCALA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_SCALA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_SCALA_SYMBOL="·"
SPACESHIP_SCALA_COLOR="#FB4934"

# Sudo
#SPACESHIP_SUDO_SHOW=true
SPACESHIP_SUDO_SHOW=false
SPACESHIP_SUDO_PREFIX=""
SPACESHIP_SUDO_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_SUDO_SYMBOL="↯"
SPACESHIP_SUDO_COLOR="#FABD2F"

# Swift
SPACESHIP_SWIFT_ASYNC=true
SPACESHIP_SWIFT_SHOW_LOCAL=false
#SPACESHIP_SWIFT_SHOW_LOCAL=true
SPACESHIP_SWIFT_SHOW_GLOBAL=false
SPACESHIP_SWIFT_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_SWIFT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_SWIFT_SYMBOL="🐦·"
SPACESHIP_SWIFT_SYMBOL="·"
SPACESHIP_SWIFT_COLOR="#F05138"

# Terraform
#SPACESHIP_TERRAFORM_SHOW=true
SPACESHIP_TERRAFORM_SHOW=false
SPACESHIP_TERRAFORM_ASYNC=true
SPACESHIP_TERRAFORM_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_TERRAFORM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_TERRAFORM_SYMBOL="🛠️·"
SPACESHIP_TERRAFORM_COLOR=105

# TIME
SPACESHIP_TIME_SHOW=false
SPACESHIP_TIME_PREFIX="at·"
SPACESHIP_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_TIME_FORMAT=false
SPACESHIP_TIME_12HR=false
SPACESHIP_TIME_COLOR="#FABD2F"

# Username (user)
SPACESHIP_USER_SHOW=true
SPACESHIP_USER_PREFIX="with·"
SPACESHIP_USER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_USER_COLOR="#FABD2F"
SPACESHIP_USER_COLOR_ROOT="#FB4934"

# V vlang
#SPACESHIP_VLANG_SHOW=true
SPACESHIP_VLANG_SHOW=false
SPACESHIP_VLANG_ASYNC=true
SPACESHIP_VLANG_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_VLANG_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_VLANG_SYMBOL="V"
SPACESHIP_VLANG_COLOR="#458588"

# Virtualenv (env)
SPACESHIP_VENV_SHOW=true
SPACESHIP_VENV_ASYNC=false
SPACESHIP_VENV_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_VENV_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_VENV_SYMBOL="·"
SPACESHIP_VENV_SYMBOL="·"
SPACESHIP_VENV_GENERIC_NAMES=(virtualenv venv .venv)
SPACESHIP_VENV_COLOR="#458588"

# Xcode
SPACESHIP_XCODE_ASYNC=true
#SPACESHIP_XCODE_SHOW_LOCAL=true
SPACESHIP_XCODE_SHOW_LOCAL=false
SPACESHIP_XCODE_SHOW_GLOBAL=false
SPACESHIP_XCODE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_XCODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_XCODE_SYMBOL="🛠·"
SPACESHIP_XCODE_COLOR="#458588"

# Zig
#SPACESHIP_ZIG_SHOW=true
SPACESHIP_ZIG_SHOW=false
SPACESHIP_ZIG_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_ZIG_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_ZIG_SYMBOL="⚡"
SPACESHIP_ZIG_COLOR="#FABD2F"
