# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Uncomment for debuf with `zprof`
# zmodload zsh/zprof

# Flex on the ubuntu users
#neofetch

# ZSH Ops
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FCNTL_LOCK
setopt +o nomatch
# setopt autopushd

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Start zim
source "$ZIM_HOME/init.zsh"

# Async mode for autocompletion
ZSH_AUTOSUGGEST_USE_ASYNC=true
ZSH_HIGHLIGHT_MAXLENGTH=300

source "$DOTFILES_PATH/shell/init.sh"

source $ZSH_REVERSE/reverse_search.zsh
source "$DOTFILES_PATH/shell/zsh/key-bindings.zsh"

# STARSHIP
# Spaceship prompt configuration
# Just comment a section if you want to disable it
SPACESHIP_PROMPT_ORDER=(
  # time        # Time stamps section (Disabled)
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  # package     # Package version (Disabled)
  node          # Node.js section
  ruby          # Ruby section
  elixir        # Elixir section
  # xcode       # Xcode section (Disabled)
  swift         # Swift section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  # julia       # Julia section (Disabled)
  # docker      # Docker section (Disabled)
  aws           # Amazon Web Services section
  gcloud        # Google Cloud Platform section
  venv          # virtualenv section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
  dotnet        # .NET section
  # ember       # Ember.js section (Disabled)
  kubectl       # Kubectl context section
  terraform     # Terraform workspace section
  ibmcloud      # IBM Cloud section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  # vi_mode     # Vi-mode indicator (Disabled)
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# PROMPT
#SPACESHIP_PROMPT_SYMBOL="➜"
SPACESHIP_CHAR_SYMBOL="❯"
#SPACESHIP_CHAR_SYMBOL="➜"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS="#1793D1"
SPACESHIP_CHAR_COLOR_FAILURE="#FB4934"
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_PROMPT_SUFFIXES_SHOW=true
SPACESHIP_PROMPT_DEFAULT_PREFIX="via "
SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "

# TIME
SPACESHIP_TIME_SHOW=false
SPACESHIP_TIME_PREFIX="at "
SPACESHIP_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_TIME_FORMAT=false
SPACESHIP_TIME_12HR=false
SPACESHIP_TIME_COLOR="#FABD2F"

# USER
SPACESHIP_USER_SHOW=true
SPACESHIP_USER_PREFIX="with "
SPACESHIP_USER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_USER_COLOR="#FABD2F"
SPACESHIP_USER_COLOR_ROOT="#FB4934"

# HOST
SPACESHIP_HOST_SHOW=true
SPACESHIP_HOST_PREFIX="at "
SPACESHIP_HOST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_HOST_COLOR="#98971A"

# DIR
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_PREFIX="in "
SPACESHIP_DIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DIR_TRUNC=2
SPACESHIP_DIR_TRUNC_PREFIX=".../"
SPACESHIP_DIR_COLOR="#98971A"
SPACESHIP_DIR_LOCK_SYMBOL=" "
SPACESHIP_DIR_LOCK_COLOR="#FB4934"

# GIT
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_PREFIX="on "
SPACESHIP_GIT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GIT_SYMBOL=" "
# GIT BRANCH
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_BRANCH_PREFIX="$SPACESHIP_GIT_SYMBOL"
SPACESHIP_GIT_BRANCH_SUFFIX=""
SPACESHIP_GIT_BRANCH_COLOR="#B16286"
# GIT STATUS
SPACESHIP_GIT_STATUS_SHOW=true
SPACESHIP_GIT_STATUS_PREFIX=" ["
SPACESHIP_GIT_STATUS_SUFFIX="]"
SPACESHIP_GIT_STATUS_COLOR="#FB4934"
SPACESHIP_GIT_STATUS_UNTRACKED="?"
SPACESHIP_GIT_STATUS_ADDED="+"
SPACESHIP_GIT_STATUS_MODIFIED="!"
SPACESHIP_GIT_STATUS_RENAMED="»"
SPACESHIP_GIT_STATUS_DELETED="✘"
SPACESHIP_GIT_STATUS_STASHED="S"
SPACESHIP_GIT_STATUS_UNMERGED=""
SPACESHIP_GIT_STATUS_AHEAD="⇡"
SPACESHIP_GIT_STATUS_BEHIND="⇣"
SPACESHIP_GIT_STATUS_DIVERGED="⇕"

# PACKAGE
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_PACKAGE_PREFIX=" "
SPACESHIP_PACKAGE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_PACKAGE_SYMBOL=" "
SPACESHIP_PACKAGE_COLOR="#FB4934"

# NODE
SPACESHIP_NODE_SHOW=false
SPACESHIP_NODE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_NODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_NODE_SYMBOL="⬢ "
SPACESHIP_NODE_SYMBOL=" "
SPACESHIP_NODE_DEFAULT_VERSION=""
SPACESHIP_NODE_COLOR="#75AC64"

# RUBY
SPACESHIP_RUBY_SHOW=false
SPACESHIP_RUBY_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_RUBY_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_RUBY_SYMBOL="💎 "
SPACESHIP_RUBY_SYMBOL=" "
SPACESHIP_RUBY_COLOR="#D30001"

# ELM
SPACESHIP_ELM_SHOW=false
SPACESHIP_ELM_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_ELM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_ELM_SYMBOL="🌳 "
SPACESHIP_ELM_COLOR="#83A598"

# ELIXIR
SPACESHIP_ELIXIR_SHOW=false
SPACESHIP_ELIXIR_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_ELIXIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_ELIXIR_SYMBOL=" "
SPACESHIP_ELIXIR_COLOR="#458588"

# XCODE
SPACESHIP_XCODE_SHOW_LOCAL=false
SPACESHIP_XCODE_SHOW_GLOBAL=false
SPACESHIP_XCODE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_XCODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_XCODE_SYMBOL="🛠 "
SPACESHIP_XCODE_COLOR="#007FF2"

# SWIFT
SPACESHIP_SWIFT_SHOW_LOCAL=false
SPACESHIP_SWIFT_SHOW_GLOBAL=false
SPACESHIP_SWIFT_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_SWIFT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_SWIFT_SYMBOL="🐦 "
SPACESHIP_SWIFT_SYMBOL=" "
SPACESHIP_SWIFT_COLOR="#F05138"

# GOLANG
SPACESHIP_GOLANG_SHOW=false
SPACESHIP_GOLANG_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_GOLANG_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_GOLANG_SYMBOL="🐹 "
SPACESHIP_GOLANG_SYMBOL=" "
SPACESHIP_GOLANG_COLOR="#6EC1D0"

# PHP
SPACESHIP_PHP_SHOW=false
SPACESHIP_PHP_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PHP_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_PHP_SYMBOL="🐘 "
SPACESHIP_PHP_SYMBOL=" "
SPACEHIP_PHP_COLOR="#777BB3"

# RUST
SPACESHIP_RUST_SHOW=false
SPACESHIP_RUST_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_RUST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_RUST_SYMBOL="𝗥 "
SPACESHIP_RUST_SYMBOL=" "
SPACESHIP_RUST_COLOR="#EB4601"

# HASKELL
SPACESHIP_HASKELL_SHOW=false
SPACESHIP_HASKELL_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_HASKELL_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_HASKELL_SYMBOL=" "
SPACESHIP_HASKELL_COLOR="#FB4934"

# JULIA
SPACESHIP_JULIA_SHOW=false
SPACESHIP_JULIA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_JULIA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_JULIA_SYMBOL=" "
SPACESHIP_JULIA_COLOR="#B8BB26"

# DOCKER
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_DOCKER_PREFIX="on "
SPACESHIP_DOCKER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_DOCKER_SYMBOL="🐳 "
SPACESHIP_DOCKER_SYMBOL=" "
SPACESHIP_DOCKER_COLOR="#2391E5"
# DOCKER CONTEXT
SPACESHIP_DOCKER_CONTEXT_SHOW=false
SPACESHIP_DOCKER_CONTEXT_PREFIX="·("
SPACESHIP_DOCKER_CONTEXT_SUFFIX=")"

# AWS
SPACESHIP_AWS_SHOW=false
SPACESHIP_AWS_PREFIX="using·"
SPACESHIP_AWS_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_AWS_SYMBOL=" "
SPACESHIP_AWS_COLOR=208

# GCLOUD
SPACESHIP_GCLOUD_SHOW=false
SPACESHIP_GCLOUD_PREFIX="using·"
SPACESHIP_GCLOUD_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GCLOUD_SYMBOL=" "
SPACESHIP_GCLOUD_COLOR=26

# VENV
SPACESHIP_VENV_SHOW=true
SPACESHIP_VENV_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_VENV_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_VENV_SYMBOL="(.venv) · "
SPACESHIP_VENV_GENERIC_NAMES=".venv"
SPACESHIP_VENV_COLOR="#458588"

# CONDA
SPACESHIP_CONDA_SHOW=false
SPACESHIP_CONDA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_CONDA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_CONDA_SYMBOL="🅒·"
SPACESHIP_CONDA_COLOR="#458588"
SPACESHIP_CONDA_VERBOSE=true

# PYENV
SPACESHIP_PYENV_SHOW=false
SPACESHIP_PYENV_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PYENV_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_PYENV_SYMBOL="🐍 "
SPACESHIP_PYENV_SYMBOL="·"
SPACESHIP_PYENV_COLOR="#3570A0"

# DOTNET
SPACESHIP_DOTNET_SHOW=false
SPACESHIP_DOTNET_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_DOTNET_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DOTNET_SYMBOL=".NET·"
SPACESHIP_DOTNET_COLOR="#6A4097"

# EMBER
SPACESHIP_EMBER_SHOW=false
SPACESHIP_EMBER_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_EMBER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_EMBER_SYMBOL=" "
SPACESHIP_EMBER_COLOR="210"

# KUBERNETES
SPACESHIP_KUBECTL_SHOW=false
SPACESHIP_KUBECTL_PREFIX="at·"
SPACESHIP_KUBECTL_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECTL_SYMBOL="☸️··"
SPACESHIP_KUBECTL_COLOR="#EBDBB2"
# KUBERNETES VERSION
SPACESHIP_KUBECTL_VERSION_SHOW=false
SPACESHIP_KUBECTL_VERSION_PREFIX=" "
SPACESHIP_KUBECTL_VERSION_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECTL_VERSION_COLOR="#8EC07C"
# KUBERNETES CONTEXT
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_KUBECONTEXT_PREFIX="at·"
SPACESHIP_KUBECONTEXT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_KUBECONTEXT_COLOR="#8EC07C"
SPACESHIP_KUBECONTEXT_NAMESPACE_SHOW=true
SPACESHIP_KUBECONTEXT_COLOR_GROUPS=""

# GRADLE
SPACESHIP_GRADLE_SHOW=false
SPACESHIP_GRADLE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_GRADLE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GRADLE_SYMBOL="⬡·"
SPACESHIP_GRADLE_DEFAULT_VERSION=""
SPACESHIP_GRADLE_COLOR="#B8BB26"
SPACESHIP_GRADLE_JVM_SHOW=true
SPACESHIP_GRADLE_JVM_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_GRADLE_JVM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GRADLE_JVM_SYMBOL=" ·"
SPACESHIP_GRADLE_JVM_DEFAULT_VERSION=""
SPACESHIP_GRADLE_JVM_COLOR="#D3869B"

# MAVEN
SPACESHIP_MAVEN_SHOW=false
SPACESHIP_MAVEN_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_MAVEN_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_MAVEN_SYMBOL="𝑚·"
SPACESHIP_MAVEN_DEFAULT_VERSION=""
SPACESHIP_MAVEN_COLOR="#FABD2F"
SPACESHIP_MAVEN_JVM_SHOW=true
SPACESHIP_MAVEN_JVM_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_MAVEN_JVM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_MAVEN_JVM_SYMBOL="☕️·"
SPACESHIP_MAVEN_JVM_DEFAULT_VERSION=""
SPACESHIP_MAVEN_JVM_COLOR="#D3869B"

# TERRAFORM
SPACESHIP_TERRAFORM_SHOW=false
SPACESHIP_TERRAFORM_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_TERRAFORM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_TERRAFORM_SYMBOL="🛠️·"
SPACESHIP_TERRAFORM_COLOR="#7740B6"

# IBM CLOUD
SPACESHIP_IBMCLOUD_SHOW=false
SPACESHIP_IBMCLOUD_PREFIX="using·"
SPACESHIP_IBMCLOUD_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_IBMCLOUD_SYMBOL="·"
SPACESHIP_IBMCLOUD_COLOR=039

# EXECUTION
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_PREFIX="took "
SPACESHIP_EXEC_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_EXEC_TIME_COLOR="#FABD2F"
SPACESHIP_EXEC_TIME_ELAPSED=2

# BATTERY
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_BATTERY_PREFIX=""
SPACESHIP_BATTERY_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_BATTERY_SYMBOL_CHARGING="⇡"
SPACESHIP_BATTERY_SYMBOL_DISCHARGING="⇣"
SPACESHIP_BATTERY_SYMBOL_FULL="•"
SPACESHIP_BATTERY_THRESHOLD=10

# JOBS
SPACESHIP_JOBS_SHOW=false
SPACESHIP_JOBS_PREFIX=""
SPACESHIP_JOBS_SUFFIX=""
SPACESHIP_JOBS_SYMBOL="✦"
SPACESHIP_JOBS_COLOR="#458588"
SPACESHIP_JOBS_AMOUNT_PREFIX=""
SPACESHIP_JOBS_AMOUNT_SUFFIX=""
SPACESHIP_JOBS_AMOUNT_THRESHOLD=1

# EXIT CODE
SPACESHIP_EXIT_CODE_SHOW=false
SPACESHIP_EXIT_CODE_PREFIX=""
SPACESHIP_EXIT_CODE_SUFFIX=""
SPACESHIP_EXIT_CODE_SYMBOL="✘"
SPACESHIP_EXIT_CODE_COLOR="#FB4934"

# VI_MODE
SPACESHIP_VI_MODE_SHOW=true
SPACESHIP_VI_MODE_PREFIX=""
SPACESHIP_VI_MODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_VI_MODE_INSERT="[I]"
SPACESHIP_VI_MODE_NORMAL="[N]"
SPACESHIP_VI_MODE_COLOR="white"

# Spaceship Prompt
autoload -Uz promptinit && promptinit
prompt restore # theme spaceship

# fnm
export PATH=/home/osito/.fnm:$PATH
eval "`fnm env`"
