#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#----------DUPLICATE PROGRAM AUTOSTART----------
killall sxhkd 2>/dev/null
killall polybar 2>/dev/null
killall -qw picom 2>/dev/null
killall -q dunst 2>/dev/null
killall nm-applet 2>/dev/null
#killall -q volumeicon 2>/dev/null
#killall -q cbatticon 2>/dev/null
killall -q udiskie 2>/dev/null
killall greenclip 2>/dev/null
killall paperview 2>/dev/null
killall redshift-gtk 2>/dev/null # Or use redshift &
#----------AUTOSTART----------
wmname LG3D &
bash ~/.config/polybar/launch.sh 
sxhkd &
#cbatticon -u 5 &
#volumeicon &
#sh ~/.fehbg &
#picom &
#paperview ~/Pictures/Gifs/bmp/sakura 5 0 0 1920 1080  ~/Pictures/Gifs/bmp/daft 5 1920 0 1920 1080 &
paperview ~/Pictures/Gifs/bmp/sakura 5 0 0 1920 1080  ~/Pictures/Gifs/bmp/ae 5 1920 0 1920 1080 &
bash ~/.config/dunst/load.sh # Load dunst configuration
redshift-gtk &
nm-applet &
blueman-applet &
#setxkbmap -layout us,us -variant altgr-intl,dvorak-intl -option grp:alt_shift_toggle &
setxkbmap -layout us -variant altgr-intl &
xsetroot -cursor_name left_ptr &
greenclip daemon &
udiskie -t &

#----------ListProviders----------
GPU=`xrandr --listproviders | grep "Provider 1"`
if [[ $GPU ]]; then
  xrandr --listproviders 1 0
  DRI_PRIME=1
fi

#----------MONITORS----------
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0

#bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 0

#----------BSPWM Configuration----------
#bspc config border_radius                8
bspc config border_radius                 10
bspc config border_width                  2
bspc config window_gap                    5
#bspc config top_padding                   10
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
#bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#----------BSPWM Coloring----------
bspc config normal_border_color 	      "#3C3836"
bspc config active_border_color 	      "#3C3836"
bspc config focused_border_color 	      "#458588"
bspc config presel_feedback_color	      "#458588"
bspc config urgent_border_color 	      "#CC241D"


#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-secondary_HDMI1)

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a Zathura state=tiled follow=on

#bspc rule -a Code desktop='^2' #open VSCcode on workspace 2
bspc rule -a Code follow=on
bspc rule -a Soffice desktop='^4' #open any libreoffice suit, move to workspace 6
#bspc rule -a firefox desktop='^6' #open firefox, move to desktop 6
bspc rule -a pomotroid state=floating rectangle=600+503+145

bspc rule -a Font-manager state=floating follow=on center=true
bspc rule -a gnome-calculator state=floating follow=on center=true rectangle=400x400+0+0
bspc rule -a android-studio state=floating follow=on center=true
bspc rule -a Gcolor3 state=floating follow=on center=true
